FROM golang:1.17 as builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /go/src/github.com/NewMirai/go-MAL-scraper
COPY go.sum go.mod ./
RUN go mod download
COPY . .
RUN go build -o /go/bin main.go cleanUtils.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /go/bin ./
CMD ["./main"]
